### ISSUE TITLE
Cookie error ?

### ISSUE THREAD

**Issue by ldb2000** [y3nd/bouygues-sms#6]
hi,

This is a very good job that has been done. I have tried but sometimes I am getting some issue with a simple example that you have given.. Here is the error message

/home/pi/node_modules/bouygues-sms/index.js:15
      var jsessionid = response.headers["set-cookie"][0].match(/JSESSIONID=(.*); Path=\/cas\/; HttpOnly/)
                                                     ^

TypeError: Cannot read property '0' of undefined
    at req (/home/pi/node_modules/bouygues-sms/index.js:15:54)
    at Request.request [as _callback] (/home/pi/node_modules/bouygues-sms/index.js:117:19)
    at Request.self.callback (/home/pi/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/pi/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/pi/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:293:19)

Thanks a lot for your help.

**Comment by y3nd** [comment]
Should be fixed in https://github.com/y3nd/bouygues-sms/pull/7
