### ISSUE TITLE
Erreur: TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by N0ury** [y3nd/bouygues-sms#9]
Salut Yoann,

le site Bouygues a dû changer. J'ai l'erreur:

[Bouygues-SMS] > Authenticating..
[Bouygues-SMS] > GET - https://www.mon-compte.bouyguestelecom.fr/cas/login - {}
/Users/nb/Downloads/node_modules/bouygues-sms/index.js:15
      var jsessionid = response.headers["set-cookie"][1].match(/JSESSIONID=(.*); Path=\/cas\/; HttpOnly/)
                                                     ^

TypeError: Cannot read property '1' of undefined
    at /Users/nb/Downloads/node_modules/bouygues-sms/index.js:15:54
    at Request._callback (/Users/nb/Downloads/node_modules/bouygues-sms/index.js:117:19)
    at Request.self.callback (/Users/nb/Downloads/node_modules/request/request.js:185:22)
    at Request.emit (node:events:365:28)
    at Request.<anonymous> (/Users/nb/Downloads/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:365:28)
    at IncomingMessage.<anonymous> (/Users/nb/Downloads/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:471:28)
    at IncomingMessage.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)

Je ne sais pas si tu as encore la possibilité de voir ça.

'accent circonflexe est sur l'indice [1]. Le copier-coller l'a décalé

**Comment by y3nd** [comment]
Salut,

Je ne suis plus chez cet opérateur, par conséquent je ne suis plus en mesure de maintenir la librairie.
Le site a dû effectivement changer il y a quelques années déjà.

Je reste disponible pour d'éventuelles pull requests.

**Comment by Arno-Develop** [comment]
Hello,
Merci pour ton outil dans un premier temps, j'ai apporté des corrections sur la fonction LogIn et ajouté une fonction LogOut.
[index.zip](https://github.com/y3nd/bouygues-sms/files/8327731/index.zip)

**Comment by y3nd** [comment]
@Arno-Develop 
Merci pour ta participation au projet. Tu peux forker et faire une pull request afin d'ajouter tes modifications.
